# Generated by Django 5.0.2 on 2025-04-09 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('dessert_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPrice',
            fields=[
                ('special_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Veggie',
            fields=[
                ('veggie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('daily_special_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number_of_sides', models.IntegerField()),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specials.specialprice')),
            ],
        ),
        migrations.CreateModel(
            name='DailySpecial',
            fields=[
                ('daily_special_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('dessert_1', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_dessert_1', to='specials.dessert')),
                ('dessert_2', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_dessert_2', to='specials.dessert')),
                ('dessert_3', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_dessert_3', to='specials.dessert')),
                ('dessert_4', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_dessert_4', to='specials.dessert')),
                ('a_special', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_a', to='specials.special')),
                ('b_special', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_b', to='specials.special')),
                ('c_special', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_c', to='specials.special')),
                ('d_special', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_d', to='specials.special')),
                ('e_special', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_e', to='specials.special')),
                ('f_special', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_f', to='specials.special')),
                ('veggie_1', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_1', to='specials.veggie')),
                ('veggie_2', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_2', to='specials.veggie')),
                ('veggie_3', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_3', to='specials.veggie')),
                ('veggie_4', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_4', to='specials.veggie')),
                ('veggie_5', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_5', to='specials.veggie')),
                ('veggie_6', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_6', to='specials.veggie')),
                ('veggie_7', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_7', to='specials.veggie')),
                ('veggie_8', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_8', to='specials.veggie')),
            ],
        ),
    ]
