# Generated by Django 5.0.2 on 2025-04-09 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyspecial',
            options={'ordering': ['-date'], 'verbose_name': 'Daily Special', 'verbose_name_plural': 'Daily Specials'},
        ),
        migrations.AlterModelOptions(
            name='dessert',
            options={'verbose_name': 'Dessert', 'verbose_name_plural': 'Desserts'},
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'verbose_name': 'Special', 'verbose_name_plural': 'Specials'},
        ),
        migrations.AlterModelOptions(
            name='specialprice',
            options={'verbose_name': 'Special Price', 'verbose_name_plural': 'Special Prices'},
        ),
        migrations.AlterModelOptions(
            name='veggie',
            options={'verbose_name': 'Vegetable', 'verbose_name_plural': 'Vegetables'},
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Dessert Name'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Special Name'),
        ),
        migrations.AlterField(
            model_name='special',
            name='number_of_sides',
            field=models.IntegerField(verbose_name='Number of Sides'),
        ),
        migrations.AlterField(
            model_name='special',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specials.specialprice', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='specialprice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Price Description'),
        ),
        migrations.AlterField(
            model_name='specialprice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price Amount'),
        ),
        migrations.AlterField(
            model_name='veggie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Veggie Name'),
        ),
    ]
