# Generated by Django 5.0.2 on 2025-04-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0002_alter_dailyspecial_options_alter_dessert_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspecial',
            name='veggie_10',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_10', to='specials.veggie'),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='veggie_9',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_9', to='specials.veggie'),
        ),
    ]
