# Generated by Django 5.0.2 on 2025-04-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0004_alter_special_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
    ]
