# Generated by Django 5.0.2 on 2025-04-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0005_alter_special_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspecial',
            name='a_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Special A with side'),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='b_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Special B with side'),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='c_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Special C with side'),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='d_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Special D with side'),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='e_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Special E with side'),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='f_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Special F with side'),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='veggie_11',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_11', to='specials.veggie'),
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='veggie_12',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_12', to='specials.veggie'),
        ),
    ]
