# Generated by Django 5.0.2 on 2025-04-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0006_dailyspecial_a_special_w_side_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialPrice',
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='a_special',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_a', to='specials.special'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='a_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='w/side'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='b_special',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_b', to='specials.special'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='b_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='w/side'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='c_special',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_c', to='specials.special'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='c_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='w/side'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='d_special',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_d', to='specials.special'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='d_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='w/side'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='dessert_1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_dessert_1', to='specials.dessert'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='dessert_2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_dessert_2', to='specials.dessert'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='dessert_3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_dessert_3', to='specials.dessert'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='dessert_4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_dessert_4', to='specials.dessert'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='e_special',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_e', to='specials.special'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='e_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='w/side'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='f_special',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_f', to='specials.special'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='f_special_w_side',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='w/side'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_1', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_10',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_10', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_11',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_11', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_12',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_12', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_2', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_3', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_4', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_5',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_5', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_6',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_6', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_7',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_7', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_8',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_8', to='specials.veggie'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='veggie_9',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_special_veggie_9', to='specials.veggie'),
        ),
    ]
