# Generated by Django 5.0.2 on 2025-04-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0007_delete_specialprice_alter_dailyspecial_a_special_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyspecial',
            old_name='dessert_1',
            new_name='w_dessert',
        ),
        migrations.RenameField(
            model_name='dailyspecial',
            old_name='dessert_2',
            new_name='x_dessert',
        ),
        migrations.RenameField(
            model_name='dailyspecial',
            old_name='dessert_3',
            new_name='y_dessert',
        ),
        migrations.RenameField(
            model_name='dailyspecial',
            old_name='dessert_4',
            new_name='z_dessert',
        ),
    ]
