# Generated by Django 5.0.2 on 2025-04-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0008_rename_dessert_1_dailyspecial_w_dessert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={'ordering': ['name'], 'verbose_name': 'Dessert', 'verbose_name_plural': 'Desserts'},
        ),
        migrations.AlterModelOptions(
            name='special',
            options={'ordering': ['name'], 'verbose_name': 'Special', 'verbose_name_plural': 'Specials'},
        ),
        migrations.AlterModelOptions(
            name='veggie',
            options={'ordering': ['name'], 'verbose_name': 'Vegetable', 'verbose_name_plural': 'Vegetables'},
        ),
        migrations.AddField(
            model_name='dailyspecial',
            name='special_image',
            field=models.ImageField(blank=True, upload_to='special_images/'),
        ),
    ]
