# Generated by Django 5.0.2 on 2025-04-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specials', '0009_alter_dessert_options_alter_special_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='w_extra',
            field=models.CharField(blank=True, default='', max_length=26, verbose_name='W/ Extra'),
        ),
        migrations.AlterField(
            model_name='veggie',
            name='name',
            field=models.CharField(max_length=24, verbose_name='Veggie Name'),
        ),
    ]
